cricketers_data = [
    {"name": "Sachin Tendulkar", "runs": 34357, "country": "India", "batting_style": "Right-hand"},
    {"name": "Ricky Ponting", "runs": 27483, "country": "Australia", "batting_style": "Right-hand"},
    {"name": "Jacques Kallis", "runs": 25534, "country": "South Africa", "batting_style": "Right-hand"},
    {"name": "Virat Kohli", "runs": 25550, "country": "India", "batting_style": "Right-hand"},
    {"name": "Kumar Sangakkara", "runs": 28016, "country": "Sri Lanka", "batting_style": "Left-hand"},
    {"name": "Mahela Jayawardene", "runs": 25957, "country": "Sri Lanka", "batting_style": "Right-hand"},
    {"name": "Brian Lara", "runs": 22358, "country": "West Indies", "batting_style": "Left-hand"},
    {"name": "Rahul Dravid", "runs": 24208, "country": "India", "batting_style": "Right-hand"},
    {"name": "Inzamam-ul-Haq", "runs": 20580, "country": "Pakistan", "batting_style": "Right-hand"},
    {"name": "AB de Villiers", "runs": 20014, "country": "South Africa", "batting_style": "Right-hand"},
    {"name": "Chris Gayle", "runs": 19000, "country": "West Indies", "batting_style": "Left-hand"},
    {"name": "Sanath Jayasuriya", "runs": 21032, "country": "Sri Lanka", "batting_style": "Left-hand"},
    {"name": "MS Dhoni", "runs": 17092, "country": "India", "batting_style": "Right-hand"},
    {"name": "Adam Gilchrist", "runs": 15683, "country": "Australia", "batting_style": "Left-hand"},
    {"name": "Steve Waugh", "runs": 18496, "country": "Australia", "batting_style": "Right-hand"},
    {"name": "Allan Border", "runs": 17698, "country": "Australia", "batting_style": "Left-hand"},
    {"name": "Hashim Amla", "runs": 18500, "country": "South Africa", "batting_style": "Right-hand"},
    {"name": "David Warner", "runs": 12000, "country": "Australia", "batting_style": "Left-hand"},
    {"name": "Shahid Afridi", "runs": 11196, "country": "Pakistan", "batting_style": "Right-hand"},
    {"name": "Yuvraj Singh", "runs": 11778, "country": "India", "batting_style": "Left-hand"},
    {"name": "Sourav Ganguly", "runs": 18433, "country": "India", "batting_style": "Left-hand"},
    {"name": "Stephen Fleming", "runs": 15000, "country": "New Zealand", "batting_style": "Left-hand"},
    {"name": "Mohammad Yousuf", "runs": 17225, "country": "Pakistan", "batting_style": "Right-hand"},
    {"name": "Graeme Smith", "runs": 17000, "country": "South Africa", "batting_style": "Left-hand"},
    {"name": "Javed Miandad", "runs": 16213, "country": "Pakistan", "batting_style": "Right-hand"},
    {"name": "Virender Sehwag", "runs": 17253, "country": "India", "batting_style": "Right-hand"},
    {"name": "Michael Clarke", "runs": 16000, "country": "Australia", "batting_style": "Right-hand"},
    {"name": "Alastair Cook", "runs": 15646, "country": "England", "batting_style": "Left-hand"},
    {"name": "Ross Taylor", "runs": 16000, "country": "New Zealand", "batting_style": "Right-hand"},
    {"name": "Mohammad Azharuddin", "runs": 15593, "country": "India", "batting_style": "Right-hand"},
    {"name": "Gary Kirsten", "runs": 14289, "country": "South Africa", "batting_style": "Left-hand"},
    {"name": "Aravinda de Silva", "runs": 14500, "country": "Sri Lanka", "batting_style": "Right-hand"},
    {"name": "Tillakaratne Dilshan", "runs": 15500, "country": "Sri Lanka", "batting_style": "Right-hand"},
    {"name": "Andrew Strauss", "runs": 13000, "country": "England", "batting_style": "Left-hand"},
    {"name": "Martin Crowe", "runs": 12488, "country": "New Zealand", "batting_style": "Right-hand"},
    {"name": "Clive Lloyd", "runs": 11000, "country": "West Indies", "batting_style": "Left-hand"},
    {"name": "Dean Jones", "runs": 9500, "country": "Australia", "batting_style": "Right-hand"},
    {"name": "Mark Waugh", "runs": 16000, "country": "Australia", "batting_style": "Right-hand"},
    {"name": "Michael Hussey", "runs": 14000, "country": "Australia", "batting_style": "Left-hand"},
    {"name": "Jonathan Trott", "runs": 9000, "country": "England", "batting_style": "Right-hand"},
    {"name": "Shakib Al Hasan", "runs": 12000, "country": "Bangladesh", "batting_style": "Left-hand"},
    {"name": "Joe Root", "runs": 18000, "country": "England", "batting_style": "Right-hand"},
    {"name": "Kane Williamson", "runs": 15000, "country": "New Zealand", "batting_style": "Right-hand"},
    {"name": "Ben Stokes", "runs": 8500, "country": "England", "batting_style": "Left-hand"},
    {"name": "Babar Azam", "runs": 9000, "country": "Pakistan", "batting_style": "Right-hand"},
    {"name": "Marnus Labuschagne", "runs": 5000, "country": "Australia", "batting_style": "Right-hand"},
    {"name": "Jason Holder", "runs": 6500, "country": "West Indies", "batting_style": "Right-hand"},
    {"name": "Quinton de Kock", "runs": 9500, "country": "South Africa", "batting_style": "Left-hand"},
    {"name": "Eoin Morgan", "runs": 11500, "country": "England", "batting_style": "Left-hand"},
    {"name": "Angelo Mathews", "runs": 12000, "country": "Sri Lanka", "batting_style": "Right-hand"},
    {"name": "Faf du Plessis", "runs": 11500, "country": "South Africa", "batting_style": "Right-hand"},
    {"name": "Brendon McCullum", "runs": 14000, "country": "New Zealand", "batting_style": "Right-hand"},
    {"name": "Mohammad Rizwan", "runs": 6500, "country": "Pakistan", "batting_style": "Right-hand"},
    {"name": "Jos Buttler", "runs": 10500, "country": "England", "batting_style": "Right-hand"},
    {"name": "Rohit Sharma", "runs": 15500, "country": "India", "batting_style": "Right-hand"},
    {"name": "Shubman Gill", "runs": 4000, "country": "India", "batting_style": "Right-hand"},
    {"name": "KL Rahul", "runs": 8000, "country": "India", "batting_style": "Right-hand"},
    {"name": "Ravindra Jadeja", "runs": 7000, "country": "India", "batting_style": "Left-hand"},
    {"name": "Dinesh Karthik", "runs": 10000, "country": "India", "batting_style": "Right-hand"},
    {"name": "Shreyas Iyer", "runs": 5500, "country": "India", "batting_style": "Right-hand"},
    {"name": "Rishabh Pant", "runs": 5000, "country": "India", "batting_style": "Left-hand"},
    {"name": "Hardik Pandya", "runs": 4500, "country": "India", "batting_style": "Right-hand"},
    {"name": "Glenn Maxwell", "runs": 9500, "country": "Australia", "batting_style": "Right-hand"},
    {"name": "Marcus Stoinis", "runs": 3500, "country": "Australia", "batting_style": "Right-hand"},
    {"name": "David Miller", "runs": 9500, "country": "South Africa", "batting_style": "Left-hand"},
    {"name": "Kieron Pollard", "runs": 11000, "country": "West Indies", "batting_style": "Right-hand"},
    {"name": "Andre Russell", "runs": 8000, "country": "West Indies", "batting_style": "Right-hand"},
    {"name": "Mushfiqur Rahim", "runs": 12000, "country": "Bangladesh", "batting_style": "Right-hand"},
    {"name": "Tamim Iqbal", "runs": 13000, "country": "Bangladesh", "batting_style": "Left-hand"},
    {"name": "Shane Watson", "runs": 15000, "country": "Australia", "batting_style": "Right-hand"},
    {"name": "Imam-ul-Haq", "runs": 5500, "country": "Pakistan", "batting_style": "Left-hand"},
    {"name": "Usman Khawaja", "runs": 8500, "country": "Australia", "batting_style": "Left-hand"},
    {"name": "Dimuth Karunaratne", "runs": 9000, "country": "Sri Lanka", "batting_style": "Left-hand"},
    {"name": "Travis Head", "runs": 7000, "country": "Australia", "batting_style": "Left-hand"},
    {"name": "Aiden Markram", "runs": 6500, "country": "South Africa", "batting_style": "Right-hand"},
    {"name": "Pat Cummins", "runs": 2500, "country": "Australia", "batting_style": "Right-hand"},
    {"name": "Tim Southee", "runs": 3000, "country": "New Zealand", "batting_style": "Right-hand"},
    {"name": "Chris Woakes", "runs": 4000, "country": "England", "batting_style": "Right-hand"},
    {"name": "Shai Hope", "runs": 7000, "country": "West Indies", "batting_style": "Right-hand"},
    {"name": "Sikandar Raza", "runs": 6500, "country": "Zimbabwe", "batting_style": "Right-hand"},
    {"name": "Mohammad Nabi", "runs": 5000, "country": "Afghanistan", "batting_style": "Right-hand"},
    {"name": "Najibullah Zadran", "runs": 3500, "country": "Afghanistan", "batting_style": "Left-hand"},
    {"name": "Kevin O'Brien", "runs": 7000, "country": "Ireland", "batting_style": "Right-hand"},
    {"name": "Paul Stirling", "runs": 8500, "country": "Ireland", "batting_style": "Right-hand"}
]
